### ISSUE TITLE
How to produce results in Table 3 of the paper

### ISSUE THREAD

**Issue by 22nicolet** [romainloiseau/Helix4D#4]
Hello,

To produce the IoU results by class in Table 3, are there any changes I need to make to the yaml files? After running the pretrained model the iou value comes out to be a mean constant instead of a nine-value IoU array by class.

Also, is there a reason the transformer block only uses key and value vectors but not a query vector?

Thanks!

**Comment by romainloiseau** [comment]
Hello,

1. You can print whatever you want in the IoU file `romainloiseau/Helix4D/helix4d/callbacks/loggers/monitoring.py` fonction `log_ious`. Otherwise, IoU array for individual classes are logged by the tensorboard logger under the name `f"image/confmat/{tag}"`.
2. We justified the design choices in the [paper](https://arxiv.org/abs/2206.08194). The algorithm is detailled in equation 9 and the ablation study table 4 line d demonstrates a drop of 2 mIoU points by using key and query: 
    > (d) w. Queries: we modify our simplified transformer to associate a query for each voxel along with keys and values, and use key-queries compatibilities. This does not affect the run-time and slightly decreases the performance.

Best
